# Generated by Django 2.1.5 on 2021-01-20 17:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
